/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-08 09:51:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Section_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Section_info</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"b-example-divider\"></div>\r\n");
      out.write(" 		<div class=\"container px-5 py-4\" id=\"icon-grid\">\r\n");
      out.write("    		<div class=\"row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 g-4 py-4\">\r\n");
      out.write("      			<div class=\"col d-flex align-items-start\">\r\n");
      out.write("        		<img src=\"./img/user.png\" width=\"50px\" height=\"50px\" class=\"bi text-muted flex-shrink-0 me-3\">\r\n");
      out.write("        		");
 	String id = request.getParameter("id"); 
					if(id == null) {
				
      out.write("\r\n");
      out.write("        		<div>\r\n");
      out.write("          			<h3 class=\"fw-bold mb-0 fs-4\">회원정보</h3>\r\n");
      out.write("          			<p style=\"padding:5px\">로그인을 통해 재밌는 <br> 방탈출 게임을 즐기세요!</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        		");
 } else {
       			
      out.write("\r\n");
      out.write("       			<div>\r\n");
      out.write("          			<h3 class=\"fw-bold mb-0 fs-4\">회원정보</h3>\r\n");
      out.write("          			<p style=\"padding:5px\">ID: ");
      out.print( id );
      out.write("</p>\r\n");
      out.write("        		</div>\r\n");
      out.write("        		");
 }
       			
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("      			<div class=\"col d-flex align-items-start\">\r\n");
      out.write("        		<img src=\"./img/game.png\" width=\"50px\" height=\"50px\" class=\"bi text-muted flex-shrink-0 me-3\">\r\n");
      out.write("        		<div>\r\n");
      out.write("          			<h3 class=\"fw-bold mb-0 fs-4\">게임 목록</h3>\r\n");
      out.write("          			<p style=\"padding:5px\">NEW 보통의 하루 <br> SOON 건망증</p>\r\n");
      out.write("   				</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("      			<div class=\"col d-flex align-items-start\">\r\n");
      out.write("        		<img src=\"./img/review.png\" width=\"50px\" height=\"50px\" class=\"bi text-muted flex-shrink-0 me-3\">\r\n");
      out.write("        		<div>\r\n");
      out.write("          			<h3 class=\"fw-bold mb-0 fs-4\">나의 리뷰</h3>\r\n");
      out.write("          			<p style=\"padding:5px\">당신의 리뷰는 큰 도움이 됩니다.</p>\r\n");
      out.write("          			<form action=\"ReviewServlet\" method=\"post\">\r\n");
      out.write("          				 <div class=\"d-grid gap-2 d-md-flex justify-content-md-end\">\r\n");
      out.write("  							<input type=\"submit\" class=\"btn btn-secondary\" value=\"리뷰 더보기\">\r\n");
      out.write("						</div>\r\n");
      out.write("          			</form>\r\n");
      out.write("        		</div>\r\n");
      out.write("        	</div>\r\n");
      out.write("   		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
